# scrutinizer-ci.com configuration
imports:
    - javascript
    - php
filter:
    excluded_paths: [js/vendor/*, js/jqplot/*, js/openlayers/*, js/codemirror/*, js/tracekit/*, js/sprintf.js]
build:
    dependencies:
        before:
            - composer install
            - ./vendor/bin/phpcs --config-set installed_paths `pwd`/vendor/phpmyadmin/coding-standard
    tests:
        override:
            -
                command: './vendor/bin/phpcs  --standard=PMAStandard ./ --report=checkstyle --report-file=cs-data --ignore=*/vendor/*,*/codemirror/*,*/openlayers/*,*/jqplot/*,*/build/*'
                analysis:
                    file: 'cs-data'                 # The reporter filename
                    format: 'php-cs-checkstyle'     # The supported format by Scrutinizer
