language: php
php:
  - "5.4"
  - "5.3"
  - "5.2"
sudo: false
before_script:
  - export PATH=~/.composer/vendor/bin/:$PATH
  - mysql -uroot -e "CREATE DATABASE test;"
  - if [ $TRAVIS_PHP_VERSION != "5.2" ] ; then composer install --dev --no-interaction ; fi
  - ./scripts/generate-mo --quiet
script:
  - if [ $TRAVIS_PHP_VERSION != "5.2" ] ; then ./vendor/bin/phpunit --configuration phpunit.xml.nocoverage ; else phpunit --configuration phpunit.xml.nocoverage ; fi
  - git ls-files | grep '\.php$' | xargs -n1 php -l
cache:
  directories:
    - $HOME/.composer/cache/
